# Generated by Django 3.0.6 on 2020-05-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200519_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='contract',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
