# Generated by Django 2.1.7 on 2020-05-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20200527_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='contract',
            field=models.CharField(choices=[('6 Months', '6 Months'), ('1 Year', '1 Year'), ('2 Years', '2 Years'), ('More than 2 Years', 'More than 2 Years')], max_length=20, null=True),
        ),
    ]
