# Generated by Django 2.1.7 on 2020-06-02 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_review_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='author',
        ),
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
